#+Title: Team workflow git
#+author: Antoine Romain Dumont
#+STARTUP: indent
#+STARTUP: hidestars odd

* Introduction
Here is one possible team workflow!
I'm not saying it's the ultimate way and those that do not follow will
burn! Feel free to discuss it and/or patch it!

For simplicity's readings, i talk about master as of the final branch
we need to merge into. It's just to simplify and give a name.
You can, of course, translate this by replacing master by a release branch.

* For each developer, here is how we start the retrieval of a project
*** Retrieve the repository needed
*** Clone this repository
***** Go to the desired folder to receive the clone of the repository
Exemple : 
#+BEGIN_SRC sh
cd ~/repositories/pro/
#+END_SRC
***** Then clone the repository
#+BEGIN_SRC sh
git clone adress-of-the-repository
#+END_SRC

Example:
#+BEGIN_SRC sh
git clone https://ardumont@github.com/ardumont/my-org-files.git
#+END_SRC sh

*** We create a branch from master to develop our fix or our functionality.
#+BEGIN_SRC sh
git checkout -b trigram-user/branch-name
#+END_SRC

Example : 
#+BEGIN_SRC sh
git checkout -b adu/doSomeStuff
#+END_SRC
*** Regularly, return to master to synchronize the source.
#+BEGIN_SRC sh
# Return to master
git checkout master
# Synchronize your local repository and your workspace
# with the content of the distant repository
git pull
#+END_SRC

Remark :
If it refuses (git explains everything it does and why sometimes, it
does not want to do what you ask it to do), you may have forgotten one
step. You may, for example, have changes locally that you did not
commit to your index.

So, before returning to master, make sure that :
- you have commited everything in your index for your branch 
#+BEGIN_SRC sh
git add the-thing-you-wanna-commit-but-unstable another-thing-to-commit-but-unstable ...
git commit -m "Filthy commit not stable, need to amend it later"
# later, when everything is ok
# git add the-thing-you-wanna-commit-stable \ 
# another-thing-to-commit-stable ... 
# amend the commit
# git commit --amend
#+END_SRC
- or dropped it if it is useless to you
#+BEGIN_SRC sh
rm the-thing-you-wanna-commit-but-unstable another-thing-to-commit-but-unstable ...
#+END_SRC
- or another option, stash it! 
#+BEGIN_SRC sh
git stash
# and later when everything is ok, just unstash it
# git stash pop
#+END_SRC

Remark 2:
These commands are your best friends, ask them to help you out!

#+BEGIN_SRC sh
git status
#+END_SRC
and/or 
#+BEGIN_SRC sh
gitk --all
#+END_SRC
and/or
#+BEGIN_SRC sh
git log
#+END_SRC
*** Now, we're synchronized with master, we return to our branch and merge these changes inside our branch.
***** Return to our branch
#+BEGIN_SRC sh
git checkout trigram-user/branch-name
#+END_SRC
***** Merge the content of master into our branch
#+BEGIN_SRC sh
git merge master
#+END_SRC

Everything ok ?
If everything is merging without problems, continue.

Else, there were conflits during merge.
We must fix these conflicts manually.

Either you use the tool git offers you
#+BEGIN_SRC sh
git mergetool
#+END_SRC
Or, you open your favourite ide or editor and choose what you want to keep or not depending on the situation.
When all conflicts are resolved and that all your tests are ok, add
all the files modified to the index, commit and that's all folks!

#+BEGIN_SRC sh
git status
git add yourFileModified yourFile2Modified
git commit
#+END_SRC

***** Why must i merge master into my branch ?
******* To make sure what i'm doing still works with the latest code!
******* If not, you will surely break the code into master when you'll merge your fix or dev!
***** What if master is broken ?
******* It depends on the policy of your project.
******* If your policy is "Every commit is stable (all tests ok)" then it's not possible... or not!
********* Very strong assertion : Master must be stable!
*********** How can we be sure of such assertion ?
************* Continous integration !
************* Code review tool such as Gerrit!
*** I've done my dev, what do i do ?
***** Check these assertions :
******* Is all your code commited to your branch?
******* Is your dev done?
******* Are all your unit-tests ok?
******* Are all your functional-tests or integration-tests ok ?
******* Does your app deploy and work as expected ?
*** Ok then, it's time to merge into master.
***** Return to master 
#+BEGIN_SRC sh
git checkout master
#+END_SRC
***** To avoid some later merging, check you're up-to-date with master
#+BEGIN_SRC sh
git pull
#+END_SRC
If everything is already up-to-date, then pass to the next step.
Else, return to the previous step.
***** Merge the content of the "merging branch" into master
#+BEGIN_SRC sh
git merge trigram-user/branch-name
#+END_SRC
At this point, it will only do a fast forward, that's just a moving
forward the master pointer to the last commit of your branch (because
your master branch did not advance between your checkout and the merge command).
***** Send your modifications to master! 
#+BEGIN_SRC sh
git push
#+END_SRC
***** What if there are problems ?
It's not a real problem, it just means "somebody, somebody put something in your drink"!
It means really that someone pushed something before you did finish
your merge.

You must once again merge. But this time, it will be fast.
As your branch and the master are already merged, when you will pull
some code, git will automagically merge what it can from master and
leave you eventuals conflicts to resolve.

#+BEGIN_SRC sh
# synchronize with everybody... (needs somebody to love!)
git pull
# fix eventual merge conflicts and check your tests 
# add the merged files to the index (git add) 
# and commit (git commit)
git push
#+END_SRC
***** Now, you're done!!!
