#+BLOG: tony-blog
#+POSTID: 481
#+DATE: [2012-12-22 Sat 14:20]
#+TITLE: Arduino/Clodiuno - command a LED from the clojure REPL
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+TAGS: clodiuno, clojure, arduino, emacs, geek
#+CATEGORY: arduino, clojure, geek
#+DESCRIPTION: What was my difficulties bootstraping arduino/clodiuno.

Now that the setup hell is gone, here i will describe "my first interaction" to make my arduino uno talk with a simple led.

Source: https://github.com/ardumont/arduino-lab

* Circuit
First we create a simple circuit.

Plug your LED on the pin 13 of the arduino board.

*Beware*, the LED is polarized, so
- the longer branch (+) goes into the 13 pin
- and the other one goes inside the GND just beside.

*No Led*
If you have no LED, it's no big deal as there is already one in it.

* Pre-requisites
** Plug your arduino board in your usb

** Upload the firmata sketch

Open up the arduino IDE and load the appropriate Firmata sketch from File > Examples.
I used StandardFirmata_2_2_forUNO_0_3 because I have an Uno board, but your version may vary.

** In Ubuntu GNU/Linux

Make sure you have correctly linked your device with an appropriate name
#+BEGIN_SRC sh
tony@dagobah(0.44,) 18:06:22 ~/org/clodiuno (master) $ ls -l /dev/ttyS42
lrwxrwxrwx 1 root root 12 2012-06-03 15:34 /dev/ttyS42 -> /dev/ttyACM0
#+END_SRC

Else it will not be seen.

* Setup
Here is my project's setup:

#+BEGIN_SRC clj
(defproject arduino-lab "1.0.0-SNAPSHOT"
  :description "Mess around with arduino from the comfort of the repl
  :dependencies [[org.clojure/clojure "1.3.0"]
                 [clodiuno "0.0.3-SNAPSHOT"]
                 [serial-port "1.1.2"]]
  :native-dependencies [[org.clojars.samaaron/rxtx "2.2.0.1"]]
  :dev-dependencies [[native-deps "1.0.5"]]
  :jvm-opts ["-Djava.library.path=./native/linux/x86/"
             "-d32"])
#+END_SRC

Fetch the dependencies:
#+BEGIN_SRC sh
lein deps
#+END_SRC

Start emacs and start the repl:
#+BEGIN_SRC sh
M-x clojure-jack-in
#+END_SRC
* Now some reality
Now i can do light up and down a led on my arduino uno from the repl!

Open the repl:
#+BEGIN_SRC clj
user> (use 'clodiuno.core 'clodiuno.firmata)
nil
#+END_SRC

Open the board:
#+BEGIN_SRC clj
user>(def board (arduino :firmata "/dev/ttyS42"))
#'user/board
#+END_SRC

Now you can see something along the line:
#+BEGIN_SRC clj
user> board
#<Ref@9652e4: {:digital-in {2 (0 0 0 0 0 0 0 0), 1 (0 0 0 0 0 0 0 0), 0 (0 0 0 0 0 0 0 0)}, :version [2 2], :port #<RXTXPort /dev/ttyS42>, :interface :firmata}>
#+END_SRC

We must first set the built-in 13 pin (the led) to OUTPUT mode.
#+BEGIN_SRC clj
user> (pin-mode board 13 OUTPUT)
nil
#+END_SRC

Then play with the board, may the light be
#+BEGIN_SRC clj
user> (digital-write board 13 HIGH)
nil
#+END_SRC

... or not:
#+BEGIN_SRC clj
user> (digital-write board 13 LOW)
nil
#+END_SRC

* Result

http://youtu.be/T3ooJXkHRlg
