#+BLOG: tony-blog
#+POSTID: 903
#+DATE: [2013-01-05 sam. 15:53]
#+TITLE: Programming in haskell - ch7 - Higher-order functions 2/2
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+TAGS: haskell, exercises, functional-programming
#+CATEGORY: haskell, exercises, functional-programming
#+DESCRIPTION: Learning haskell and solving problems using reasoning and 'repl'ing
#+STARTUP: indent
#+STARTUP: hidestars

For the first exercises, [[http://adumont.fr/blog/pih-ch7-higher-order-functions-12/][see this post]].

* curry/uncurry
#+begin_quote
Without looking at the standard prelude, define the higher-order library function curry that converts a function on pairs into a curried function, and, conversely, the function uncurry that converts a curried function with two arguments into a function on pairs.

*Hint:*
First write down the types of the two functions.
#+end_quote

* unfold
#+begin_quote
A higher-order function *unfold* that encapsulates a simple pattern of recursion for producing a list can be defined as follows:
#+begin_src haskell
unfold p h t x | p x = []
               | otherwise = h x : unfold p h t (t x )
#+end_src

That is, the function =unfold p h t= produces the empty list if the predicate =p= is true of the argument, and otherwise produces a non-empty list by applying the function =h= to give the head, and the function =t= to generate another argument that is recursively processed in the same way to produce the tail of the list.

For example, the function *int2bin* can be rewritten more compactly using *unfold* as follows:
#+begin_src haskell
int2bin = unfold (== 0) (‘mod ‘2) (‘div ‘2)
#+end_src

Redefine the functions *chop8*, *map f* and *iterate f* using unfold.
#+end_quote

** chop8
** map f
** iterate f

* transmitter
#+begin_quote
Modify the string transmitter program to detect simple transmission errors using parity bits. That is, each eight-bit binary number produced during encoding is extended with a parity bit, set to one if the number contains an odd number of ones, and to zero otherwise.
In turn, each resulting nine-bit binary number consumed during decoding is checked to ensure that its parity bit is correct, with the parity bit being discarded if this is the case, and a parity error reported otherwise.

*Hint:*
The library function =error :: String → a= terminates evaluation and displays the given string as an error message.

#+end_quote

* Test
#+begin_quote
Test your new string transmitter program from the previous exercise using a faulty communication channel that forgets the first bit, which can be modelled using the tail function on lists of bits.
#+end_quote
