#+BLOG: tony-blog
#+TITLE: Programming in haskell - ch5 - Lists comprehension - exercises
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+TAGS: haskell, exercises, functional-programming
#+CATEGORY: haskell, exercises, functional-programming
#+DESCRIPTION: Learning haskell and solving problems using reasoning and 'repl'ing
#+STARTUP: indent
#+STARTUP: hidestars odd

Exercises on the chapter 5 of the books.
We encounter :
- conditional expressions
- guarded equations
- pattern matching (tuple, list, integer)
- lambda expressions

* Halve
#+BEGIN_QUOTE
Using library functions, define a function =halve :: [a] → ([a], [a])= that splits an even-lengthed list into two halves.

For example:

> halve [1, 2, 3, 4, 5, 6]

([1, 2, 3], [4, 5, 6])
#+END_QUOTE

The function *splitAt* already provides the means to split one list from a given position.
Here our position is the half of the length of the list, which gives:

#+BEGIN_SRC text
halve :: [a] -> ([a], [a])
halve xs = splitAt (length xs `div` 2) xs
#+END_SRC

Executing in the repl, we obtain:
#+BEGIN_SRC text
*Ch4> halve [1, 2, 3, 4, 5, 6]
([1,2,3],[4,5,6])
#+END_SRC

* safetail
#+BEGIN_QUOTE
Consider a function =safetail :: [a] → [a]= that behaves as the library function *tail*, except that safetail maps the empty list to itself, whereas *tail* produces an error in this case.

Define *safetail* using:
- a conditional expression;
- guarded equations;
- pattern matching.

*Hint:* make use of the library function *null*.
#+END_QUOTE

* logical disjunction
#+BEGIN_QUOTE
In a similar way to *∧*, show how the logical disjunction operator *∨* can be defined in four different ways using pattern matching.
#+END_QUOTE

* conditional expression
#+BEGIN_QUOTE
Redefine the following version of the conjunction operator using conditional expressions rather than pattern matching:

True ∧ True = True

_ ∧ _       = False
#+END_QUOTE

* conditional expression 2
#+BEGIN_QUOTE
Do the same for the following version, and note the difference in the number of conditional expressions required:

True ∧ b  = b

False ∧ _ = False
#+END_QUOTE

* Curried function and lambda expression
#+BEGIN_QUOTE
Show how the curried function definition =mult x y z = x ∗ y ∗ z= can be understood in terms of lambda expressions.
#+END_QUOTE
