#+DATE: [2013-07-12 ven. 21:45]
#+OPTIONS: toc:nil
#+CATEGORIES: org-trello, org-mode, emacs, trello, tools
#+DESCRIPTION: Synchronize your trello board from emacs
#+TITLE: org-trello - 2-way sync org & trello
#+LAYOUT: post

For some time now, I wanted to learn [[https://www.gnu.org/software/emacs/manual/html_node/elisp/index.html][Emacs-lisp]] some [[https://github.com/ardumont/emacs-live-packs][more than I already did]].
As I dayly use emacs, I think it was the logical course of action.

And, as I:
- already use [[http://orgmode.org/][org-mode]] a lot (even for blogging this very moment)
- kept encountering [[https://trello.com/][trello]] for team organisation
- don't like to duplicate informations
- can't expect everybody to try and learn [[https://www.gnu.org/software/emacs/][emacs]] and [[%20%5B%5Bhttp://orgmode.org/%5D%5Borg-mode%5D%5D%20][org-mode]]
- [[https://trello.com/][trello]] exposes a [[https://trello.com/docs/][public API]]

I thought "what the hell, let's do this!".
And here is the result: [[https://github.com/org-trello/org-trello][org-trello]], an [[http://orgmode.org/][org-mode]] [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Minor-Modes.html][minor-mode]] to permit the synchronization between a [[https://trello.com/][trello]] board and an [[http://orgmode.org/][org-mode]] file (and vice versa).

* Demo!

** Synchronize one entity

http://youtu.be/ILPs74L5LFU

** Setup org-mode file to work with one trello board

http://youtu.be/2PT8K1HG-eY

** Synchronize one complete entity and move entity according to status

http://youtu.be/H8DXm5BLaD0

** Synchronize from org-mode file to trello

http://youtu.be/d6SATWzhQhs

** Create board and sync

http://youtu.be/6k4zRm6t8ZY
** Synchronize from trello to org-mode file

http://youtu.be/-ldo8gvhaTY

** Install org-trello

http://youtu.be/e3NzllAHbHY

** Setup key and token

http://youtu.be/ReUp1Wn5scc

* Sources

[[https://github.com/ardumont/org-trello][source]]

* Releases

Released on:
- marmalade - http://www.marmalade-repo.org/packages/org-trello (stable)
- melpa - http://melpa.milkbox.net/ (snapshot)
