#+title: Truth about violence
#+source: http://www.samharris.org/blog/item/the-truth-about-violence

* Avoid dangerous people and dangerous places
- Mastering martial arts (rules) does not necessary means you will be able to defend yourself (outside, no rules applies)
- You cannot assess one's power
- In social dominance contest, keep your head cold and do not bother answering.
- Over all, never threaten your opponent (it's what the assaillant wants to justify his/her position)
- "Keep your inner ape on a very tight leash"
- Try and defuse unnecessary conflicts
- Trust your gut feelings. If something seems not right, do not give in to your social skills and take a hike.

* Do not defend your property
- View the violence as an invitation to die or unfortunately kill someone
- Avoiding violence is the only concern

* Respond immediately and escape
- Do whatever you can to avoid a physical confrontation, but the moment avoidance fails, attack explosively for the purposes of escape.
- In this situation, do not waste time in pointless discussion with a predator.
- If a predator tries to control your move, go against the impulse to comply (it will only get worse) and try at best to explode in action.
- Do not forget that the main goal is to escape.
