#+BLOG: tony-blog
#+POSTID: 1324
#+DATE: [2014-03-01 sam. 17:29]
#+TITLE: Feedback loop
#+AUTHOR: ardumont
#+DESCRIPTION: Later is too late!
#+CATEGORIES: feedback, tools, stumpwm, emacs, org-mode, tmux, firefox, keysnail, git, vagrant, make, script
#+TAGS: feedback, tools, stumpwm, emacs, org-mode, tmux, firefox, keysnail, git, vagrant, make, script

* TL;DR
Use the right tools for the right job. And feedback all the way!

* DISCLAIMER
I present my set of tools.
In no way do I claim these are the supreme tools. As always, your mileage may vary.
The only claim I make is that they can let me be fast.

* Introduction

As I already explains time and time again (links), I'm feedback driven.

I want to:
- have feedback immediately after I executed a command/function
- know if I'm wrong now
- believe... (oops, bad context)

* Why?

Because ideas are as fast as poping out of nowhere as disappearing into nowhere...

Sometimes, it's right to think and think again and go implementing later...
And sometimes, it's better to go think and tinker along the way too...

Links to find:
Bref Victor   -> ...
Chris Granger -> lighttable

* How

For this, I use these tools:

- GNU/Linux

Stable, user-friendly, extendable, reproducible...
These are qualities unavoidable to do what I do.

- Emacs

It's not an editor, it's an environment highly extendable.

- StumpWM

The *emacs* window manager!

- Org-mode

To do things, one has to organized

- [[Http://Tmux.Sourceforge.Net/][Tmux]]

The *emacs* terminal session manager!

- Firefox with KeySnail

firefox, the emacs way!

- Git

- Vagrant

-
