#+BLOG: tony-blog
#+POSTID: 1318
#+DATE: [2014-02-28 ven. 01:30]
#+TITLE: Personal Generic Service Wrapper
#+AUTHOR: ardumont
#+DESCRIPTION: Generic need to start/stop/status/restart binary/script
#+CATEGORY: script, GNU/Linux, feedback, service, personal
#+TAGS: script, GNU/Linux, feedback, service, personal

* Problem

I often need to start/stop/restart/status userland command.

* Context

I'm running under:
- [[http://www.debian.org/][Debian]]-derivative system ([[http://ubuntu.com/][Ubuntu]], [[http://linuxmint.com/][Linux-Mint]])
- [[https://en.wikipedia.org/wiki/Window_manager][Window Manager]] ([[http://www.nongnu.org/stumpwm/][StumpWM]]) - this does not impact anything. This explains why I want to reload my configuration and need to restart some program.

* Example

For example, the [[https://github.com/mirsal/nm-applet][nm-applet]] (small graphical applet to deal with network)

You can do this way:
#+begin_src sh
killall nm-applet && killall nm-applet
#+end_src

or this way:
#+begin_src sh
pidof nm-applet | xargs kill -KILL
#+end_src

In any case, for each script/command, you have to repeat the same code.

* Generic service wrapper

We can factorize this a simple service wrapper script that orchestrates this behaviour.

** Use
Some typical usage would be:

#+begin_src sh
service.sh nm-applet start|stop|status|restart
#+end_src

** Script

#+begin_src sh
#!/bin/bash
# Use: $0 {start|stop|restart|status}
# Generic Service Wrapper
# Example:
# $0 <htop|nm-applet|some-personal-script> {start|stop|status|restart}

### functions

# Application that this service wraps
APP=$1
shift

# Send a signal to the nm-applet pid (KILL to kill, 0 to know if it's alive)
app-send() {
    SIG=$1
    mypid=$(pidof $APP)
    [ -z "$mypid" ] && exit 1   # no pid so not running
    kill -$SIG $mypid && exit 0 # if pid exists and the process exists, will return 0
    exit 1 # otherwise problem
}

# Stop application
app-stop() {
    $(app-send KILL)
}

# Start application
app-start() {
    $APP
}

# status
app-status() {
    $(app-send 0)
    ( [ $? = 0 ] && echo "$APP is running!" ) || echo "$APP is not running!"
}

### run

case "$1" in
    start)
        app-start
        app-status
        ;;

    stop)
        app-stop
        app-status
        ;;

    restart)
        app-stop
        app-start
        ;;

    status)
        app-status
        ;;

    *)
	echo "Usage: $0 <APP> {start|stop|restart|status}" >&2
	exit 1
	;;
esac
#+end_src

[[https://github.com/ardumont/sh/blob/master/service/service.sh][Source]]

** Example usage

I use it in my *.stumpwmrc* configuration file to restart the [[https://github.com/mirsal/nm-applet][nm-applet]] service.
This way, when I reload my [[http://www.nongnu.org/stumpwm/][StumpWM]] configuration, no new instance is spawned. I have exactly one.

#+begin_src lisp
(run-shell-command "~/bin/wifi/nm-applet.sh restart")
#+end_src

where nm-applet.sh simply wraps the call to service.sh:
#+begin_src sh
#!/bin/bash
# Use: $0 {start|stop|restart|status}
# Service Wrapper around nm-applet

~/bin/service/service.sh nm-applet $*
#+end_src

[[https://github.com/ardumont/dot-files/blob/master/.stumpwmrc#L184][Use in my stumpwm configuration]]

* What about command with arguments?

At the moment, the need has only appeared for command without parameters.

In theory, one would have to:
- add a small parsing step to retrieve the command name for the *stop* and *status* events

- and keep feeding the full command to the *start* and *restart* ones.

Contributions are welcome.
