#+LAYOUT: post
#+DATE: [2012-12-29 sam. 13:49]
#+TITLE: Activate/Deactivate touchpad from the shell
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+CATEGORIES: howto, tools, shell
#+DESCRIPTION: Show how to activate/deactivate touchpad depending on the soft you use
#+STARTUP: indent
#+STARTUP: hidestars

A new need has come for me.
I want to activate or deactivate the touchpad from the shell.

In this post, I will concentrate on how to trigger on/off the touchpad from the shell.

* Pre-requisites
The package *xinput*.
It should already be installed.

Just in case:
#+begin_src sh
sudo aptitude install xinput
#+end_src

* Manual
Here is the script to manually toggle it on/off.

Actions:
- It first retrieves the status the script is given.
- If empty, it does set the *1* which means, activate it.
- Then retrieve the id of the touchpad.
- At last, trigger the on/off status depending on the status.

** code
#+INCLUDE: "~/bin/touchpad/toggle-touchpad-manual.sh" src sh
src: [[https://github.com/ardumont/sh/blob/master/stumpwm/toggle-touchpad-manual.sh][toggle-touchpad-manual.sh]]

** use

Activate the touchpad
#+begin_src sh
toggle-touchpad-manual.sh 1
#+end_src

Deactivate the touchpad
#+begin_src sh
toggle-touchpad-manual.sh 0
#+end_src

* Auto
Toggle automatically on/off the touchpad.
** code
It's almost the same script as before.
But this one does request the current status of the touchpad and then inverse the status.
For doing so, it calls the previous script one with the new status as parameter.

#+INCLUDE: "~/bin/touchpad/toggle-touchpad.sh" src sh
src: [[https://github.com/ardumont/sh/blob/master/stumpwm/toggle-touchpad.sh][toggle-touchpad.sh]]

** use
#+begin_src sh
~/bin/stumpwm/toggle-touchpad.sh
#+end_src

If enabled, the touchpad will be disabled, else it will be enabled.
* Example
This works on my:
- personal asus zenbook - ubuntu 12.10
- pro hp elitebook - ubuntu 12.10

* Conclusion

In this post, I presented how to activate/deactivate the touchpad from the shell.

In [[http://ardumont.github.io/stumpwm-touchpad][another post]], I'll present a possible orchestration using those scripts as a basic brick.
