#+BLOG: tony-blog
#+POSTID: 380
#+DATE: [2012-12-22 Sat 14:20]
#+TITLE: Howto install stumpwm and little more
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+TAGS: stumpwm, tools
#+CATEGORY: stumpwm, howto, tools
#+DESCRIPTION: howto install/setup/use stumpwm + my stumpwm configuration
#+STARTUP: indent
#+STARTUP: hidestars odd

* Introduction
** For just install, skip the intro
** What is stumpwm?
A tiling, keyboard driven X11 window manager.
Simply put, it permits you to choose what you do at any given time with key-bindings.
Another simple way to sum up: Less is more :d.
** Why?
I was lost with all the shining catch-eyes effects everywhere.

With a friend, [[https://twitter.com/#!/denislab][Denis Labaye]], we search for simpler.
We found stumpwm and it was mind blowing.
** How do i use it?
Personally, i choose to work with only one window at a time and ask for the one i want when i want it.
It's my way of seeing it but stumpwm does not limit you in this way.

For me, stump empowers you with the choice of doing anything you want your way.

The small price to pay is learning key-bindings.
Small price because you can override them so the sky is really the limit.

It's the computer that adapts to you and not the other way around.
** Goal of the article
This howto explains how to install stumpwm and the little things you have to do to login with it in the gnome display manager.
** Limits of the article
*** Targeted platform
This article is clearly oriented for a debian based distribution using a gnome display manager as the login manager.
You may use some part with other distribution but i do not know how because i didn't have the problem to solve.
*** Targeted audience
Geeky/Nerdy people who likes to make computer adapts to them and not the other way around.
*** What is stumpwm in details.
[[http://www.nongnu.org/stumpwm/][What is it?]]
* How to install
** Install stumpwm from CLI
#+BEGIN_SRC sh
sudo apt-get install stumpwm
#+END_SRC
** Add a new entry to gdm
We need to add an entry menu to gdm for stumpwm so that we can log in with it.

For this we add the file /usr/share/xsessions/stumpwm.desktop
#+BEGIN_SRC sh
sudo emacs -nw /usr/share/xsessions/stumpwm.desktop
#+END_SRC

Content of the file:
#+BEGIN_SRC txt
[Desktop Entry]
        Exec=stumpwm
        TryExec=stumpwm
        Name=stumpwm
        Comment=The Mouseless Window Manager!
#+END_SRC

Here is a simple script to do that in one shot (feel free to patch):
#+INCLUDE: "/home/tony/bin/deploy/deploy-stumpwm.sh" src sh

src: [[https://github.com/ardumont/sh/blob/master/deploy/deploy-stumpwm.sh][deploy-stumpwm.sh]]
** Logout from gdm
Gdm will reload.
At next login, when you'll choose your user to log in, you will be proposed a new entry "stumpwm" at the bottom of the screen (it may depend on your theme).
Choose it and log in.
** Stumpwm starts
At the top right corner, you'll only see a help message inviting you to type "CTRL-t ?" (Control and t pressed at the same time followed by a pressure on 't') for a presentation of all the simple commands you need to start.
* How to improve itb
** Some simple commands
*** Syntax
**** C for Control
**** <l> for a letter
**** combination C-t for Control + t pressed together
**** C-t x for Control+t pressed together followed by a pressure on x.
*** C-t ?
List the basic commands
*** C-t c
To launch a terminal instance (xterm or gnome-terminal)
*** C-t e
To launch emacs or if it is already launched, call it to display before every other window.
*** C-t t
To make the window behind the current one pass before and vice-versa
Inside the browser, you need to escape the t to add a tab (i gives a C-t t t).
*** C-t s
Split the screen horizontally in two frames of equal size (emacs way).
You can move the window inside each frame the same way that when you have only one frame.
*** C-t Q
Cancel all the split screen.
*** C-t k
To kill a window not responding
*** C-t !
To launch a shell command not mapped yet on any binding.
*** etc...
cf. C-t ?
** Stumpwm is really cool
You can override commands simply by putting a '.stumpwmrc' at the root of your home.

Granted, the file is in lisp.
But you can understand it anyway.

Plus you can search the web for solution to your problems.
You will find some geek who already has the answer.
** My setup
The run or raise means that it only turns with one instance which is sufficient.
*** C-t f
Run or raise (only one instance at a time) firefox (f stands for firefox).
*** C-t b
Run or raise chromium (b stands for browser).
*** C-t i
Run or raise eclipse (i for ide)
*** C-t x
Run or raise gnome-terminal (x stands for xterm or any x terminal)
*** C-t o
To add a label (a letter) to each frame to move directly to this frame by typing the letter
*** C-t C-e
Launch the pdf reader (evince here)
*** C-t I
Display *ifconfig* result and display it inside a small window
*** C-t H
Display the content of */etc/hosts* inside a small window
*** C-t B
Display the content of *acpi -b*
*** C-t K
Display the keys the ssh-agents holds.
*** C-t A
Launch the scripts *ssh-add-identities* that adds the keys i work with to the ssh-agent
*** C-t C-o
Launch the image reader (here *eog*)
*** C-t n
Launch nautilus
*** C-t C-s
Launch a window screenshot.
*** etc...
** ~/.stumpwmrc

Here is my setup:

#+INCLUDE: "/home/tony/.stumpwmrc" src lisp
src: [[https://github.com/ardumont/dot-files/blob/master/.stumpwmrc][.stumpwmrc]]

* Last points
It's "emacs compatible". The prefix key is C-t whereas the prefix key of emacs is mostly C-x.
They work well together and they have a lot in common in their usability.

Here is a [[http://www.archive.org/details/TheStumpWMExperience][screencast]] which presents rapidly how to use it.
