#+Title: How to install emacs 24
#+author: Antoine R. Dumont
#+STARTUP: indent
#+STARTUP: hidestars odd

This article will show how to install rapidly emacs 24 on a ubuntu 11.10.

But before, one can ask himself...

* Why emacs?
If you're not interested, skip to the next chapter which will explain the installation process.

I came across it when i was student and used it poorly at the time.
If i remember correctly, i used it mainly for coding some ocaml projects and some LaTeX reports (i dp not like wysiwyg).

I finally stopped using it.
I can see clearly now, that i was wrong.

Indeed, i can:
** Edit lots of files out of the box (sh, java, html, etc...)
** Edit lisp files (stumpwm config, emacs config file, clojure project file, etc...)
** Edit files in archives (war, etc...) without unarchiving files.
** Code for example in clojure (setup required but we'll cover that)

** Commit my changes on the current repositories (with magit)
** Evaluate directly some computations in it (with elisp)
** Organise myself (using org-mode)
** Do some org-mode files and export them as blog articles
** Do some org-mode files and export them as presentations

** ... and surely, i can do tons more, i just do not know it yet

* How to install it?

- emacs24 (currently in development but still way stable)
- [[https://github.com/technomancy/emacs-starter-kit][emacs-starter-kit]] to help begin with emacs
- and some emacs-lisp code that permits to download and install the needed packages for my everyday use.
emacs.

** Here are the steps 
The script to change your local setup:
#+begin_src sh
#+INCLUDE: /home/tony/bin/deploy-emacs24.sh
#+end_src
This script will:
*** ask for the right to modify the file =/etc/apt/sources.list=.
*** update the repositories
*** install emacs 24
*** then do some setup (next script).

To launch the installation
#+begin_src sh
chmod +x /path/to/deploy-emacs24.sh && /path/to/deploy-emacs24.sh
#+end_src
** Script to deploy the emacs setup (call from the previous one)
#+begin_src sh
#+INCLUDE: /home/tony/bin/setup-emacs24.sh
#+end_src
This script will:
*** Generate a init.el file in your ~/.emacs.d/ directory.
This file setup your emacs
** Now boot emacs
#+begin_src sh
emacs
#+end_src
This will automatically search and install the asked packages.

