#+BLOG: tony-blog
#+POSTID: 449
#+DATE: [2012-12-22 Sat 14:20]
#+TITLE: How to install the clojure development environment
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+TAGS: clojure, emacs, leiningen, midje, tdd
#+CATEGORY: clojure
#+DESCRIPTION: howto install the clojure development environment on debian based system

In this article, we will see how to rapidly install the clojure tools in a debian-like distribution (ubuntu 11.10 for example).

* Pre-requisites
** [[http://www.gnu.org/software/emacs/][emacs]]
See this [[http://adumont.fr/blog/how-to-install-emacs-24/][previous post for installing it]]
* Installation
** [[http://clojure.org/][clojure]]
*** install
#+BEGIN_SRC sh
sudo aptitude install clojure
#+END_SRC

*Note*
=apt-get= if you do not have =aptitude= installed.

*** check
Type clojure in a shell
#+BEGIN_SRC sh
clojure
user=>
#+END_SRC

You will have a [[http://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop][repl]] in which you could ask some functions to eval.
#+BEGIN_SRC sh
user=> (+ 1 1)
2
#+END_SRC
** [[https://github.com/technomancy/leiningen][leiningen]] 1
*** install
**** The easy way
#+BEGIN_SRC sh
sudo aptitude install leiningen
#+END_SRC
If you do not have leiningen in the packages, then you must pass by the *not so hard* way.
**** The not so hard way
***** Download the script
#+BEGIN_SRC sh
wget https://raw.github.com/technomancy/leiningen/stable/bin/lein
#+END_SRC
***** Place it on your $PATH
I also like to use ~/bin.
#+BEGIN_SRC sh
export PATH=~/bin/:$PATH
#+END_SRC

I usually add this in the =~/.bashrc= file.
***** Make it executable
#+BEGIN_SRC sh
chmod 755 ~/bin/lein
#+END_SRC
***** Ask the version
This will download all it needs.
#+BEGIN_SRC sh
lein version
#+END_SRC
and finally gives you an output similar to this:
#+BEGIN_SRC sh
tony@dagobah(0.11,) 09:56:26 ~/org (master) $ lein version
Leiningen 1.7.1 on Java 1.6.0_26 Java HotSpot(TM) Client VM
#+END_SRC
*** check
#+BEGIN_SRC sh
tony@dagobah(0.16,) 13:00:07 ~ $ lein repl
REPL started; server listening on localhost port 14778
user=>
#+END_SRC

For example:
#+BEGIN_SRC sh
user=> (+ 1 1)
2
#+END_SRC
** [[https://github.com/marick/Midje/wiki/Lein-midje][lein-midje]]
*** install
This is a leiningen plugin to launch unit tests for the unit test framework [[https://github.com/marick/Midje][midje]].
#+BEGIN_SRC sh
lein plugin install lein-midje 1.0.9
#+END_SRC

*Note*
The version [lein-midje "2.0.0-SNAPSHOT"] is leiningen 2 compatible so do not use this one.
*** check
#+BEGIN_SRC sh
tony@dagobah(0.09,) 13:05:45 ~ $ lein midje --version
Couldn't find project.clj, which is needed for midje
#+END_SRC
OK
** jdk installed (either sun or openjdk)
*** install
**** openjdk
#+BEGIN_SRC sh
sudo aptitude install openjdk
#+END_SRC
**** sun jdk on ubuntu 11.04
https://github.com/ardumont/sh/blob/master/deploy-java-sun-11.04.sh
**** sun jdk on ubuntu 11.10
https://github.com/ardumont/sh/blob/master/deploy-java-sun-11.10.sh
*** check
#+BEGIN_SRC sh
tony@dagobah(0.32,) 13:04:16 ~ $ java -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) Server VM (build 20.1-b02, mixed mode)

#+END_SRC
** git (optional)
*** install
#+BEGIN_SRC sh
sudo aptitude install git
#+END_SRC
*** check
#+BEGIN_SRC sh
tony@dagobah(0.10,) 13:05:41 (129) ~ $ git version
git version 1.7.5.4
#+END_SRC
* Conclusion
We have focused on the needed steps to install the clojure environment.
You now have all the tools to develop with clojure.

In a near future, i intend to make some other blog posts to focus on:
- how to bootstrap a new clojure project using leiningen
- how to solve a simple problem in clojure and show how these tools work together
- continued integration with [[http://about.travis-ci.org/docs/user/getting-started/][travis-ci]]
- [[http://www.heroku.com/][heroku]] for the deploying part
- [[https://github.com/fogus/marginalia][marginalia]] for the documentation generation and the [[github]] integration
