#+TITLE: Polipo setup
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+TAGS: polipo, proxy, setup, tools
#+CATEGORY: proxy, tools
#+DESCRIPTION: Possible setup for polipo proxy
#+STARTUP: indent
#+STARTUP: hidestars

I have got some troubles with my network from some time now.
So here is one solution my team and I think of to overcome it.

We created a [[http://vagrantup.com/][vagrant machine]] with [[http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/polipo.html][polipo]] inside.

* Install
#+BEGIN_SRC sh
sudo aptitude install polipo
#+END_SRC

* Make it a service
#+BEGIN_SRC sh
sudo aptitude install chkconfig
#+END_SRC

#+BEGIN_SRC sh
sudo chkconfig polipo on
#+END_SRC
* Setup
First, we will install the server part, then the client.

** Server
When installing via ubuntu, the default setup is admittedly good.
After all, so they say if we're confident with the first lines of the =/etc/polipo/config=.

#+BEGIN_SRC sh
# Sample configuration file for Polipo. -*-sh-*-

# You should not need to edit this configuration file; all configuration
# variables have reasonable defaults.
#+END_SRC

I'm confident with those default but I need to make some modifications regarding who is gonna use our proxy.

*** Open the proxy
We permit remote connections to the proxy.

#+BEGIN_SRC sh
proxyAddress=0.0.0.0
#allowedClients = 127.0.0.1, 192.168.0.0/24, 192.168.33.0/24
#+END_SRC

*Note*
No access restriction regarding ip is done yet because I shamefully admit that I did not succeeded yet.

(It's the second line where you can detail the ip or the range of ips you authorize to use the proxy)

*** Adding authentication

I want machine to authenticate in the proxy to use it.
For this, add the =authCredentials= variable.

#+BEGIN_SRC sh
authCredentials=some-user:some-pass
#+END_SRC

*** Restart
At the end of the setup, restart the service.
#+BEGIN_SRC sh
sudo service polipo restart
#+END_SRC
** Client
*** Setup
Personally, I use the =/etc/environment= file.

My personal setup:
- proxy is on the =192.168.33.2= machine
- proxy listens on port =8123=.
- credentials: =some-user:some-pass=.

Resulting to this, you can add the equivalent lines to your =/etc/environment=:

#+BEGIN_SRC sh
export http_proxy="http://some-user:some-pass@192.168.33.2:8123"
export https_proxy="http://some-user:some-pass@192.168.33.2:8123"
export ftp_proxy="http://some-user:some-pass@192.168.33.2:8123"
export no_proxy="localhost,192.168.33.2,localaddress,.localdomain.com"
export HTTP_PROXY="http://some-user:some-pass@192.168.33.2:8123"
export HTTPS_PROXY="http://some-user:some-pass@192.168.33.2:8123"
export FTP_PROXY="http://some-user:some-pass@192.168.33.2:8123"
#+END_SRC

Then reload your environment.
You may need to logout and login again.

*Note*

As I use stumpwm, I personally only need to reload my stumpwm setup file (*C-t ;* then *loadrc*, or just as my settings goes, *C-t L*).

*** Check

Load a terminal and execute the command =env | grep -i proxy=, you should see something along:

#+BEGIN_SRC sh
http_proxy=http://some-user:some-pass@192.168.33.2:8123
ftp_proxy=http://some-user:some-pass@192.168.33.2:8123
FTP_PROXY=http://some-user:some-pass@192.168.33.2:8123
HTTPS_PROXY=http://some-user:some-pass@192.168.33.2:8123
https_proxy=http://some-user:some-pass@192.168.33.2:8123
no_proxy=localhost,192.168.33.2,localaddress,.localdomain.com
HTTP_PROXY=http://some-user:some-pass@192.168.33.2:8123
#+END_SRC

Then requesting to wget google, you should see something along those lines too:
#+BEGIN_SRC sh
tony@dagobah(0,09,) 17:01:11 ~/repo/perso/vms/vagrant-http-proxy $ wget http://google.fr
--2012-12-26 17:01:21--  http://google.fr/
Connecting to 192.168.33.2:8123... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.fr/ [following]
--2012-12-26 17:01:21--  http://www.google.fr/
Reusing existing connection to 192.168.33.2:8123.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `index.html'

    [ <=>                                                                                                                           ] 13 918      --.-K/s   in 0,04s

2012-12-26 17:01:21 (323 KB/s) - `index.html' saved [13918]

#+END_SRC

We see that we connect to the proxy =192.168.33.2= before requesting google.
Victory!
