#+TITLE: Polipo setup
#+AUTHOR: Antoine R. Dumont
#+OPTIONS:
#+TAGS: polipo, proxy, setup, tools
#+CATEGORY: proxy, tools
#+DESCRIPTION: Possible setup for polipo proxy
#+STARTUP: indent
#+STARTUP: hidestars

I have got some troubles with my network from some time now.
So here is one solution my team and I think of to overcome it.

We created a [[http://vagrantup.com/][vagrant machine]] with [[http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/polipo.html][polipo]] inside.

* Install
#+BEGIN_SRC sh
sudo aptitude install polipo
#+END_SRC

* Make it a service
#+BEGIN_SRC sh
sudo aptitude install chkconfig
#+END_SRC

#+BEGIN_SRC sh
sudo chkconfig polipo on
#+END_SRC
* Setup
** Client
Personally, I use the =/etc/environment= file.

My personal setup:
- proxy is on the =192.168.33.2= machine
- proxy listens on port =8123=.
- credentials: =some-user:some-pass=.

Resulting to this, you can add the equivalent lines to your =/etc/environment=:

#+BEGIN_SRC sh
export http_proxy="http://some-user:some-pass@192.168.33.2:8123"
export https_proxy="http://some-user:some-pass@192.168.33.2:8123"
export ftp_proxy="http://some-user:some-pass@192.168.33.2:8123"
export no_proxy="localhost,192.168.33.2,localaddress,.localdomain.com"
export HTTP_PROXY="http://some-user:some-pass@192.168.33.2:8123"
export HTTPS_PROXY="http://some-user:some-pass@192.168.33.2:8123"
export FTP_PROXY="http://some-user:some-pass@192.168.33.2:8123"
#+END_SRC

Then reload your environment.
You may need to logout and login again.

*Note*

As I use stumpwm, I personally only need to reload my stumpwm setup file (*C-t ;* then *loadrc*, or just as my settings goes, *C-t L*).

** Server
*** Open the proxy to clients

We permit remote connections to the proxy.

#+BEGIN_SRC sh
proxyAddress=0.0.0.0
#+END_SRC

*Note*
No access restriction regarding ip is done yet (I did not succeed in doing it).

*** Adding authentication

For this, add the =authCredentials= variable.

#+BEGIN_SRC sh
authCredentials=some-user:some-pass
#+END_SRC

*** Restart
At the end of the setup, restart the service.
#+BEGIN_SRC sh
sudo service polipo restart
#+END_SRC
